import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0002740230.01.LZZZZZZZ.jpg",
    name: "The Forgotten (Peter Decker & Rina Lazarus Novels (Paperback))",
    author: "Faye Kellerman",
    price: 15,
    originalPrice: 25,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.8,
    comment: [
      {
        name: "JohnDoe",
        comment: "Great book, highly recommend!",
      },
    ],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "TATJA GRIMS WORLD",
    author: "Vernor Vinge",
    price: 20,
    originalPrice: 30,
    isBestSeller: true,
    category: "Self Help",
    rating: 4.2,
    comment: [
      {
        name: "JaneSmith",
        comment: "Interesting read, but a bit complex.",
      },
    ],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "SHEEPFARMERS DAUGHTER (Deed of Paksenarrion, Book 1)",
    author: "Elizabeth Moon",
    price: 18,
    originalPrice: 28,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.5,
    comment: [
      {
        name: "BookLover123",
        comment: "One of my favorite fantasy series!",
      },
    ],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "COBRA STRIKE",
    author: "Timothy Zahn",
    price: 25,
    originalPrice: 35,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.8,
    comment: [
      {
        name: "Bookworm88",
        comment: "Action-packed and thrilling!",
      },
    ],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "METHUSELAH'S CHILDREN",
    author: "Robert A. Heinlein",
    price: 20,
    originalPrice: 30,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.6,
    comment: [
      {
        name: "SciFiFanatic",
        comment: "Classic science fiction!",
      },
    ],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "KILLING TIME (Star Trek (Numbered Paperback))",
    author: "Della Van Hise",
    price: 15,
    originalPrice: 25,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.2,
    comment: [
      {
        name: "Trekker123",
        comment: "Decent Star Trek story.",
      },
    ],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "CADILLAC JACK",
    author: "Larry McMurtry",
    price: 12,
    originalPrice: 22,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.7,
    comment: [
      {
        name: "WesternFan",
        comment: "Entertaining western.",
      },
    ],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "The crowd goes wild: Cartoons & stories",
    author: "Michael Maslin",
    price: 18,
    originalPrice: 28,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.0,
    comment: [
      {
        name: "ComicFan",
        comment: "Hilarious cartoons!",
      },
    ],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Utopia",
    author: "Sir Thomas More",
    price: 22,
    originalPrice: 32,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.4,
    comment: [
      {
        name: "Philosopher",
        comment: "Thought-provoking classic.",
      },
    ],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "LIFE UNIVERS EVRTH (Hitchhiker's Trilogy (Paperback))",
    author: "Douglas Adams",
    price: 25,
    originalPrice: 35,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.7,
    comment: [
      {
        name: "SciFiGeek",
        comment: "Hilarious and thought-provoking!",
      },
    ],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "American Star",
    author: "Jackie Collins",
    price: 30,
    originalPrice: 40,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.9,
    comment: [
      {
        name: "RomanceReader",
        comment: "Steamy romance novel!",
      },
    ],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "NEVERLAND",
    author: "Douglas Clegg",
    price: 28,
    originalPrice: 38,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.8,
    comment: [
      {
        name: "HorrorFan",
        comment: "Creepy and captivating!",
      },
    ],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "BOOMER",
    author: "Charles Taylor",
    price: 15,
    originalPrice: 25,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.5,
    comment: [
      {
        name: "BabyBoomer",
        comment: "Interesting perspectives on aging.",
      },
    ],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "I Wish This War Were over",
    author: "Diana O'Hehir",
    price: 18,
    originalPrice: 28,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.9,
    comment: [
      {
        name: "HistoryBuff",
        comment: "Emotionally powerful read.",
      },
    ],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "BEYOND THE STARLIT FROST",
    author: "Rebecca Brandewyne",
    price: 8,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.8,
    comment: [
      {
        name: "Anonymous",
        comment: "Great book!",
      },
    ],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Sundays at Moosewood Restaurant : Ethnic and Regional Recipes from the Cooks at the Legendary Restaurant",
    author: "Moosewood Collective",
    price: 10,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.2,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "BUM STEER",
    author: "Nancy Pickard",
    price: 15,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.5,
    comment: [
      {
        name: "John",
        comment: "Highly recommended!",
      },
    ],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "INCA GOLD",
    author: "Clive Cussler",
    price: 12,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "The Lost Years (Star Trek)",
    author: "J.M. Dillard",
    price: 20,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 4.7,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Book of Virtues",
    author: "William J. Bennett",
    price: 8,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 3.5,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "WHEN GIANTS LEARN TO DANCE:MASTERNG CHALLENGES OF STRTGY,MNGMT, CAREERS 0'SC",
    author: "Rosabeth Moss Kanter",
    price: 18,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 4.3,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Vanish With the Rose",
    author: "Barbara Michaels",
    price: 25,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 4.9,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "BROKEN DATE : BROKEN DATE",
    author: "R.L. Stine",
    price: 10,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 4.1,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "The Groom's Survival Manual",
    author: "Michael R. Perry",
    price: 12,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 4.4,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "A ROCK AND A HARD PLACE:STAR TREK NEXT GENERATION #10 (Star Trek Next Generation (Numbered))",
    author: "Peter David",
    price: 15,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 4.6,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "PRIVATE AFFAIRS",
    author: "Judith Michael",
    price: 22,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 4.8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Raise the Red Dawn",
    author: "Nancy Davis",
    price: 18,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 4.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "DYDEETOWN WORLD",
    author: "Jim Wilson",
    price: 5,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 3.7,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "RAT RACE",
    author: "Dick Frances",
    price: 14,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 4.2,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "BATTLESTATIONS (ST #31) (Star Trek (Numbered Paperback))",
    author: "Diane L. Carey",
    price: 20,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 4.3,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Foreign Studies",
    author: "Shusaku Endo",
    price: 18,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 4.1,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Hollywood Wives",
    author: "Jackie Collins",
    price: 20,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 4.2,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Treasure (Clive Cussler)",
    author: "Clive Cussler",
    price: 25,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 4.7,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "CAZALET CHRONICLES: LIGHT YEARS : CAZALET CHRONICLES: LIGHT YEARS (The Cazalet Chronicle, Vol. 1)",
    author: "Linda Howard",
    price: 30,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 4.5,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "DEEP SIX",
    author: "Clive Cussler",
    price: 22,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "FIRE IN THE MIST",
    author: "Holly Lisle",
    price: 18,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Some Can Whistle",
    author: "Larry McMurtry",
    price: 28,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.9,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "HENRY IV PART 1",
    author: "William Shakespeare",
    price: 15,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.7,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "RICHARD II",
    author: "William Shakespeare",
    price: 12,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.5,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "The American Horticultural Society Flower Finder",
    author: "Jacqueline Heriteau",
    price: 16,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.1,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "The Eagle Has Flown",
    author: "Jack Higgins",
    price: 18,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.2,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "TEXASVILLE (TIE-IN)",
    author: "Larry McMurtry",
    price: 30,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "RAISE THE TITANIC (Clive Cussler)",
    author: "Clive Cussler",
    price: 22,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "FAMILY AFFAIRS",
    author: "David Hoffman",
    price: 20,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.2,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Pentagames",
    author: "David Hillman",
    price: 18,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.9,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "West Side Story",
    author: "Irving Shulman",
    price: 25,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.9,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "BLESS THE BEASTS AND CHILDREN",
    author: "Glendon Swarthout",
    price: 15,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.6,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Meridian",
    author: "Alice Walker",
    price: 20,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.7,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Ruffled Feathers",
    author: "Taylor McCafferty",
    price: 24,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.5,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "WHO STOLE HOME PLATE? (Southside Sluggers)",
    author: "Steven Otfinoski",
    price: 28,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Gates of Paradise (Casteel)",
    author: "V.C. Andrews",
    price: 26,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.7,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "VITAL SIGNS",
    author: "Robin Cook",
    price: 30,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.9,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "TAMING",
    author: "Jude Deveraux",
    price: 22,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "TROPIC OF FEAR (NANCY DREW HARDY BOY SUPERMYSTERY 14) : TROPIC OF FEAR (Nancy Drew & Hardy Boys Super Mysteries (Paperback))",
    author: "Carolyn Keene",
    price: 25,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.7,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "The Gang They Couldn't Catch: The Story of America's Greatest Modern-Day Bank Robbers-And How They Got Away With It",
    author: "Debra Weyermann",
    price: 28,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "SWEET LA LA LAND",
    author: "Robert Campbell",
    price: 20,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.9,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Keeping The Love You Find",
    author: "Harville Hendrix",
    price: 20,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Sword Point",
    author: "Harold Coyle",
    price: 18,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Taming Charlotte",
    author: "Linda Lael Miller",
    price: 22,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.2,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Once and Always",
    author: "Judith McNaught",
    price: 25,
    originalPrice: 1000,
    isBestSeller: true,
    category: "Self Help",
    rating: 4.5,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Banner O'Brien",
    author: "Linda Lael Miller",
    price: 24,
    originalPrice: 1000,
    isBestSeller: true,
    category: "Self Help",
    rating: 4.3,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "ICEBERG",
    author: "Clive Cussler",
    price: 30,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.9,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "The DARE",
    author: "R.L. Stine",
    price: 18,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.7,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Where Are the Children?",
    author: "Mary Higgins Clark",
    price: 28,
    originalPrice: 1000,
    isBestSeller: true,
    category: "Self Help",
    rating: 4.6,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "BEAR HUG",
    author: "Jerome Doolittle",
    price: 25,
    originalPrice: 1000,
    isBestSeller: true,
    category: "Self Help",
    rating: 4.7,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Anything for Billy : A Novel",
    author: "Larry McMurtry",
    price: 20,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.9,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "MY TEACHER FRIED MY BRAINS",
    author: "Coville",
    price: 15,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Left to Die",
    author: "Dan Kurzman",
    price: 18,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "South of Haunted Dreams: A Ride Through Slavery's Old Back Yard",
    author: "Eddy L. Harris",
    price: 22,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.1,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "PERFUME",
    author: "Patrick Suskind",
    price: 28,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.3,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Until Proven Guilty",
    author: "Christine McGuire",
    price: 25,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.2,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "MY TEACHER GLOWS IN THE DARK",
    author: "Bruce Coville",
    price: 20,
    originalPrice: 1000,
    isBestSeller: true,
    category: "Self Help",
    rating: 4.8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "OUT OF THE NOOSPHERE",
    author: "Magazine Outside",
    price: 18,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Patrimony : A True Story",
    author: "Philip Roth",
    price: 24,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.9,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Terms Of Endearment",
    author: "Larry McMurtry",
    price: 26,
    originalPrice: 1000,
    isBestSeller: true,
    category: "Self Help",
    rating: 4.6,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "PEARL IN THE MIST",
    author: "V.C. Andrews",
    price: 23,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.1,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "ALISTAIR AND THE ALIEN INVASION",
    author: "Marilyn Sadler",
    price: 18,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.5,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Band of Brothers: E Company, 506th Regiment, 101st Airborne from Normandy to Hitler's Eagle's Nest",
    author: "Stephen E. Ambrose",
    price: 30,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.4,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "VIPER QUARRY",
    author: "Dean Feldmeyer",
    price: 26,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.3,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "USHER'S PASSING",
    author: "Robert McCammon",
    price: 22,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Mothers Who Think",
    author: "Camille Peri",
    price: 20,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.2,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Paradise",
    author: "Judith McNaught",
    price: 27,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.1,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Stones from the River",
    author: "Ursula Hegi",
    price: 25,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Devil's Juggler",
    author: "Murray Smith",
    price: 21,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.9,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "CRIMSON",
    author: "Shirley Conran",
    price: 20,
    originalPrice: 1000,
    isBestSeller: true,
    category: "Self Help",
    rating: 4.7,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "SECRET AT SOLAIRE",
    author: "Carolyn Keene",
    price: 22,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "The Devil's Heart",
    author: "David A. Carter",
    price: 24,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "DEATH ROW WOMEN",
    author: "Tom Kuncl",
    price: 28,
    originalPrice: 1000,
    isBestSeller: true,
    category: "Self Help",
    rating: 4.9,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "RED CELL",
    author: "Richard Marcinko",
    price: 26,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.2,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "EXPLOIT SHER HOLMS",
    author: "Arthur Conan Doyle",
    price: 30,
    originalPrice: 1000,
    isBestSeller: true,
    category: "Self Help",
    rating: 4.7,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "CS WAY WLF/SH SHDW",
    author: "Erle Stanley Gardner",
    price: 29,
    originalPrice: 1000,
    isBestSeller: true,
    category: "Self Help",
    rating: 4.8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "WAR REMEMBRANCE",
    author: "Herman Wouk",
    price: 25,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.9,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "GREASE",
    author: "Christoforo",
    price: 23,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "OATH OF FEALTY",
    author: "Larry Niven",
    price: 27,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "CLOCKS",
    author: "Agatha Christie",
    price: 21,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.9,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "The Mystery of Men",
    author: "Guy Bellamy",
    price: 24,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.1,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Playing for Love",
    author: "Jilly Johnson",
    price: 26,
    originalPrice: 1000,
    isBestSeller: true,
    category: "Self Help",
    rating: 4.5,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "YOU JUST GLOW!",
    author: "Lisa Weiss",
    price: 22,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.2,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "The INTRUDERS",
    author: "Stephen Coonts",
    price: 23,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.7,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "SEE, I TOLD YOU SO",
    author: "Rush Limbaugh",
    price: 25,
    originalPrice: 1000,
    isBestSeller: true,
    category: "Self Help",
    rating: 4.8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Ashton's Bride",
    author: "Judith O'Brien",
    price: 24,
    originalPrice: 1000,
    isBestSeller: true,
    category: "Self Help",
    rating: 4.6,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Disappearing Acts",
    author: "Terry McMillan",
    price: 20,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "The MIDNIGHT CLUB",
    author: "Christopher Pike",
    price: 22,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.9,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Tarnished gold",
    author: "V. C Andrews",
    price: 21,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.7,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "The CITY WHO FOUGHT",
    author: "Anne McCaffrey",
    price: 24,
    originalPrice: 1000,
    isBestSeller: true,
    category: "Self Help",
    rating: 4.5,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "A DIFFERENT FLESH",
    author: "Harry Turtledove",
    price: 20,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.9,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "CHILD OF THE EAGLE",
    author: "Esther Friesner",
    price: 23,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "All the Way to the Gallows",
    author: "David Drake",
    price: 26,
    originalPrice: 1000,
    isBestSeller: true,
    category: "Self Help",
    rating: 4.8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Redliners",
    author: "David Drake",
    price: 25,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "PRIVATE PARTS",
    author: "Howard Stern",
    price: 22,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.7,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Blaze of Glory",
    author: "Simon Hawke",
    price: 24,
    originalPrice: 1000,
    isBestSeller: true,
    category: "Self Help",
    rating: 4.5,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Mama",
    author: "Terry McMillan",
    price: 23,
    originalPrice: 1000,
    isBestSeller: true,
    category: "Self Help",
    rating: 4.7,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "TIGER WOODS",
    author: "Bill Gutman",
    price: 25,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.1,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "My Girl 2: A Novel",
    author: "Patricia Hermes",
    price: 20,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.9,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "To the Stars",
    author: "George Takei",
    price: 21,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.2,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "WATCHDOG AND THE COYOTES",
    author: "Bill Wallace",
    price: 22,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "You're Not What I Expected",
    author: "Polly, Ph.D. Young-Eisendrath",
    price: 24,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.3,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Q-Squared",
    author: "Peter David",
    price: 23,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "FURTHER ALONG THE ROAD LESS TRAVELED",
    author: "M. Scott Peck",
    price: 25,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.1,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "The Birthday",
    author: "John Richardson",
    price: 20,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.9,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "The NEW YEARS PARTY",
    author: "R.L. Stine",
    price: 21,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "The FACE",
    author: "R.L. Stine",
    price: 22,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "The CONFESSION",
    author: "R.L. Stine",
    price: 23,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.1,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Task Force Blue",
    author: "Richard Marcinko",
    price: 24,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.2,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "BE AN ANGEL!",
    author: "Dana Reynolds",
    price: 25,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.3,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Inheritance",
    author: "Judith Michael",
    price: 26,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.4,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Night of the Werewolf",
    author: "Franklin W. Dixon",
    price: 27,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.5,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Teach Yourself C++ in 21 Days",
    author: "Jesse Liberty",
    price: 28,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.6,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "A Civil Tongue",
    author: "Edwin. Newman",
    price: 29,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.7,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Calculus of a Single Variable",
    author: "Richard A. Hunt",
    price: 30,
    originalPrice: 1000,
    isBestSeller: true,
    category: "Self Help",
    rating: 4.8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Sweeter Than All the World",
    author: "Rudy Wiebe",
    price: 31,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 4.9,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Wallflower",
    author: "William Bayer",
    price: 32,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 5.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "The Cold Six Thousand",
    author: "James Ellroy",
    price: 33,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 5.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Tristram Shandy",
    author: "Laurence Sterne",
    price: 34,
    originalPrice: 1000,
    isBestSeller: true,
    category: "Self Help",
    rating: 5.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Doctor Zhivago",
    author: "Boris Leonidovich Pasternak",
    price: 35,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 5.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Brando: Songs My Mother Taught Me",
    author: "MARLON BRANDO",
    price: 36,
    originalPrice: 1000,
    isBestSeller: true,
    category: "Self Help",
    rating: 5.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "The Tale of the Body Thief",
    author: "Anne Rice",
    price: 37,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 5.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Savages",
    author: "Joe Kane",
    price: 38,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 5.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "The Silent Passage",
    author: "Gail Sheehy",
    price: 39,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 5.0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "The Lost World: A Novel",
    author: "Michael Crichton",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "Maybe (Maybe Not): Second Thoughts from a Secret Life",
    author: "Robert Fulghum",
    price: 6,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 6,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg",
    name: "The Story of Jane: The Legendary Underground Feminist Abortion Service",
    author: "Laura Kaplan",
    price: 10,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Self Help",
    rating: 10,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "Character Building: A Guide for Parents and Teachers",
    author: "David Isaacs",
    price: 6,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 6,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "Boredom Busters!: The Curious Kids' Activity Book (Williamson Kids Can! Series)",
    author: "Avery Hart",
    price: 8,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "Secret of the Old Well (Wiggin, Eric E. Hannah's Island, Bk. 5.)",
    author: "Eric E. Wiggin",
    price: 5,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 5,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "A Guide to the Passion: 100 Questions About The Passion of The Christ",
    author: "Tom Allen",
    price: 8,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "The Candle Magick Workbook (Library of the Mystic Arts)",
    author: "Kala Pajeon",
    price: 8,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "Practical Candleburning Rituals: Spells and Rituals for Every Purpose (Llewellyn's Practical Magick Series)",
    author: "Raymond Buckland",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "Origins of Modern Witchcraft: The Evolution of a World Religion",
    author: "Aoumiel",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "Crush Depth",
    author: "Joe Buff",
    price: 10,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 10,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "Soul Mates: Honoring the Mysteries of Love and Relationship",
    author: "Thomas Moore",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "Coldheart Canyon: A Hollywood Ghost Story",
    author: "Clive Barker",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "Running Scared",
    author: "Elizabeth Lowell",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "Am I Blue? : Coming Out from the Silence",
    author: "Marion Dane Bauer",
    price: 5,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 5,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "Ancient of Days",
    author: "Michael Bishop",
    price: 8,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "Rulers of Darkness (Rulers of Darkness)",
    author: "Steven Spruill",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "TickTock",
    author: "Dean R. Koontz",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "Fowl Play (Wwl Mystery , No 273)",
    author: "Patricia Tichenor Westfall",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "The White House Connection",
    author: "Jack Higgins",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "The Night Watch",
    author: "Sean Stewart",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "The Heart: A Memoir",
    author: "Lance Morrow",
    price: 8,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "Murder in Foggy Bottom (Truman, Margaret, Capital Crimes Series.)",
    author: "Margaret Truman",
    price: 4,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 4,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "Reckless Endangerment",
    author: "Robert K. Tanenbaum",
    price: 5,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 5,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "Storm",
    author: "Boris Starling",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "Public Secrets",
    author: "Nora Roberts",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "The Face of Deception",
    author: "Iris Johansen",
    price: 10,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 10,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "The Jasmine Trade : A Novel of Suspense Introducing Eve Diamond",
    author: "Denise Hamilton",
    price: 4,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 4,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "Frost of Heaven",
    author: "Junius Podrug",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "Home of the brave",
    author: "Joel Gross",
    price: 8,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "Texas Hero  (Code Name:  Danger) (Silhouette Intimate Moments, 1165)",
    author: "Merline Lovelace",
    price: 8,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "Last Lover",
    author: "Laura Van Wormer",
    price: 10,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 10,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "With Song",
    author: "Dorothy Garlock",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "Mistrals Daughter",
    author: "Judith Krantz",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/00607743.01.LZZZZZZZ.jpg",
    name: "The Celtic Heart",
    author: "Kathryn Marie Cocquyt",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0316748641.01.LZZZZZZZ.jpg",
    name: "Chang and Eng: A Novel",
    author: "Darin Strauss",
    price: 7,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Mystery",
    rating: 7,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0316748641.01.LZZZZZZZ.jpg",
    name: "Palomar",
    author: "Italo Calvino",
    price: 8,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Mystery",
    rating: 8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0316748641.01.LZZZZZZZ.jpg",
    name: "Ultimate Journey: Retracing the Path of an Ancient Buddhist Monk Who Crossed Asia in Search of Enlightenment (Vintage Departures)",
    author: "Richard Bernstein",
    price: 6,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Mystery",
    rating: 6,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0316748641.01.LZZZZZZZ.jpg",
    name: "Women's Reality: An Emerging Female System in a White Male Society",
    author: "Anne Wilson Schaef",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Mystery",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0316748641.01.LZZZZZZZ.jpg",
    name: "The Floating World",
    author: "Cynthia Kadohata",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Mystery",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0316748641.01.LZZZZZZZ.jpg",
    name: "The Rise and  Fall of the American Teenager",
    author: "Thomas Hine",
    price: 8,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Mystery",
    rating: 8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0316748641.01.LZZZZZZZ.jpg",
    name: "Gender Gap: Bella Abzug's Guide to Political Power for American Women",
    author: "Bella S. Abzug",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Science Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0316748641.01.LZZZZZZZ.jpg",
    name: "The Gangster of Love",
    author: "Jessica Hagedorn",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Science Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0316748641.01.LZZZZZZZ.jpg",
    name: "Kiss Sleeping Beauty Goodbye: Breaking the Spell of Feminine Myths and Models",
    author: "Madonna Kolbenschlag",
    price: 8,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Science Fiction",
    rating: 8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0316748641.01.LZZZZZZZ.jpg",
    name: "Family in Transition",
    author: "Arlene S. Skolnick",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Science Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0316748641.01.LZZZZZZZ.jpg",
    name: "Lesbian crossroads: Personal stories of lesbian struggles and triumphs",
    author: "Ruth Baetz",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Science Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0316748641.01.LZZZZZZZ.jpg",
    name: "Circling the Drain : Stories",
    author: "Amanda Davis",
    price: 5,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Science Fiction",
    rating: 5,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0316748641.01.LZZZZZZZ.jpg",
    name: "Coping With Miscarriage: A Simple, Reassuring Guide to Emotional and Physical Healing",
    author: "Mimi Luebbermann",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Science Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0316748641.01.LZZZZZZZ.jpg",
    name: "Old Jules",
    author: "Mari Sandoz",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Science Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0743242.01.LZZZZZZZ.jpg",
    name: "The Eentsy, Weentsy Spider: Fingerplays and Action Rhymes",
    author: "Joanna Cole",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Science Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0743242.01.LZZZZZZZ.jpg",
    name: "Unplugged Kitchen: A Return to the Simple, Authentic Joys of Cooking",
    author: "Viana La Place",
    price: 8,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Science Fiction",
    rating: 8,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0743242.01.LZZZZZZZ.jpg",
    name: "Farewell to My Concubine: A Novel",
    author: "Lilian Lee",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Science Fiction",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0743242.01.LZZZZZZZ.jpg",
    name: "The Forgotten: A Peter Decker/Rina Lazarus Novel",
    author: "Faye Kellerman",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Mystery",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0743242.01.LZZZZZZZ.jpg",
    name: "The CHURCH MICE & THE MOON (Church Mice & the Moon)",
    author: "Graham Oakley",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Mystery",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0743242.01.LZZZZZZZ.jpg",
    name: "Twelve Snails to One Lizard : A Tale of Mischief and Measurement",
    author: "Susan Hightower",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Mystery",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0743242.01.LZZZZZZZ.jpg",
    name: "Frindle",
    author: "Andrew Clements",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Mystery",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0743242.01.LZZZZZZZ.jpg",
    name: "MRS FRISBY AND THE RATS OF NIMH",
    author: "Robert C. O'Brien",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Mystery",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0743242.01.LZZZZZZZ.jpg",
    name: "Jennifer, Hecate, MacBeth, William McKinley and Me, Elizabeth",
    author: "E.L. Konigsburg",
    price: 123,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Mystery",
    rating: 0,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0743242.01.LZZZZZZZ.jpg",
    name: "Cats, Cats, Cats!",
    author: "Leslea Newman",
    price: 10,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Mystery",
    rating: 10,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0743242.01.LZZZZZZZ.jpg",
    name: "Better Homes and Gardens Cooking Chinese",
    author: "Better Homes and Gardens",
    price: 7,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Mystery",
    rating: 7,
    comment: [],
  },
  {
    _id: uuid(),
    img: "http://images.amazon.com/images/P/0743242.01.LZZZZZZZ.jpg",
    name: "Amy's Children",
    author: "Olga Masters",
    price: 8,
    originalPrice: 1000,
    isBestSeller: false,
    category: "Mystery",
    rating: 8,
    comment: [],
  },
];
